version: '3'

networks:
  public: {}
  private: {}

volumes:
  grafana_lib: {}
  grafana_ds: 

services:
    influxdb2:
        image: influxdb:2
        container_name: server-monitor-influxdb2
        platform: linux/amd64
        user: "1000:1000"
        ports:
            - 8086:8086
        networks:
            - public
            - private
        volumes:
            - ./data/:/root/.influxdb2
        env_file:
            - .env
        environment:
            INFLUXDB_REPORTING_DISABLED: "true"
            DOCKER_INFLUXDB_INIT_MODE: setup
            DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
            DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_DB}
            DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
            DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password 
            DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
        secrets:
            - influxdb2-admin-username
            - influxdb2-admin-password
            - influxdb2-admin-token

    telegraf:
        image: telegraf:1.32.1
        container_name: server-monitor-telegraf
        platform: linux/amd64
        networks:
            - private
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
        env_file:
            - .env

    prometheus:
        image: prom/prometheus:v2.54.1
        container_name: server-monitor-prometheus
        platform: linux/amd64
        user: "1000:1000"
        volumes:
            - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
            - ./prometheus/data/:/prometheus
            - ./alertmanager:/alertmanager
        networks:
            - server-monitor-network
        command:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus"
            - "--web.external-url=http://localhost:9090/"
        ports:
            - 9090:9090
        env_file:
            - .env

    alertmanager:
        image: prom/alertmanager:v0.27.0
        container_name: server-monitor-alertmanager
        platform: linux/amd64
        ports:
            - 9993:9093
        volumes:
            - ./alertmanager/:/etc/alertmanager/
        networks:
            - private
        restart: unless-stopped
        command:
            - '--config.file=/etc/alertmanager/config.yml'
            - '--storage.path=/alertmanager'
            - "--web.external-url=http://localhost:9993/"
        env_file:
            - .env

secrets:
    influxdb2-admin-username:
        file: ./influxdb/.env.influxdb2-admin-username
    influxdb2-admin-password:
        file: ./influxdb/.env.influxdb2-admin-password
    influxdb2-admin-token:
        file: ./influxdb/.env.influxdb2-admin-token
